// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
/// 
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcXsFM6DDwzc9pO9XOESUQ5es7D3ezQ1k',
    appId: '1:211718621497:web:72099b90674396438bc0e8',
    messagingSenderId: '211718621497',
    projectId: 'bod-er',
    authDomain: 'bod-er.firebaseapp.com',
    databaseURL: 'https://bod-er-default-rtdb.firebaseio.com',
    storageBucket: 'bod-er.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5-Gv5Md0PiPjrJgE606yYeGaNeJheb4A',
    appId: '1:211718621497:android:6d8eb6533b0249588bc0e8',
    messagingSenderId: '211718621497',
    projectId: 'bod-er',
    databaseURL: 'https://bod-er-default-rtdb.firebaseio.com',
    storageBucket: 'bod-er.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdfUHXsH4gjuvmZ01Um9oV7m-1iekM1Z8',
    appId: '1:211718621497:ios:79721f4faaf3afb18bc0e8',
    messagingSenderId: '211718621497',
    projectId: 'bod-er',
    databaseURL: 'https://bod-er-default-rtdb.firebaseio.com',
    storageBucket: 'bod-er.appspot.com',
    iosBundleId: 'com.example.bodae',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdfUHXsH4gjuvmZ01Um9oV7m-1iekM1Z8',
    appId: '1:211718621497:ios:79721f4faaf3afb18bc0e8',
    messagingSenderId: '211718621497',
    projectId: 'bod-er',
    databaseURL: 'https://bod-er-default-rtdb.firebaseio.com',
    storageBucket: 'bod-er.appspot.com',
    iosBundleId: 'com.example.bodae',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcXsFM6DDwzc9pO9XOESUQ5es7D3ezQ1k',
    appId: '1:211718621497:web:52757dca27d96ceb8bc0e8',
    messagingSenderId: '211718621497',
    projectId: 'bod-er',
    authDomain: 'bod-er.firebaseapp.com',
    databaseURL: 'https://bod-er-default-rtdb.firebaseio.com',
    storageBucket: 'bod-er.appspot.com',
  );
}
