// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
/// 
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcXsFM6DDwzc9pO9XOESUQ5es7D3ezQ1k',
    appId: '1:211718621497:web:52757dca27d96ceb8bc0e8',
    messagingSenderId: '211718621497',
    projectId: 'bod-er',
    authDomain: 'bod-er.firebaseapp.com',
    databaseURL: 'https://bod-er-default-rtdb.firebaseio.com',
    storageBucket: 'bod-er.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGZIGh2JYzD-MG7DrnwEBWhTQdxkaUrPA',
    appId: '1:892186184051:android:ef17badd42e5cbc0469d06',
    messagingSenderId: '892186184051',
    projectId: 'bodae-setup',
    storageBucket: 'bodae-setup.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0hM8-7BG4v5WGuAMrauQ-6ZqD9XUdfMQ',
    appId: '1:892186184051:ios:c3948cf1997cb0b1469d06',
    messagingSenderId: '892186184051',
    projectId: 'bodae-setup',
    storageBucket: 'bodae-setup.appspot.com',
    iosClientId: '892186184051-69q7nbbgd880etk4o6rgja2jr3b90qg8.apps.googleusercontent.com',
    iosBundleId: 'com.example.userBoder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdfUHXsH4gjuvmZ01Um9oV7m-1iekM1Z8',
    appId: '1:211718621497:ios:12557ca1767291d38bc0e8',
    messagingSenderId: '211718621497',
    projectId: 'bod-er',
    databaseURL: 'https://bod-er-default-rtdb.firebaseio.com',
    storageBucket: 'bod-er.appspot.com',
    iosClientId: '211718621497-d938juqpvlqc77kg9vod36kbn5t5028v.apps.googleusercontent.com',
    iosBundleId: 'com.example.userBoder',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcXsFM6DDwzc9pO9XOESUQ5es7D3ezQ1k',
    appId: '1:211718621497:web:e8d3fb7b564ac7048bc0e8',
    messagingSenderId: '211718621497',
    projectId: 'bod-er',
    authDomain: 'bod-er.firebaseapp.com',
    databaseURL: 'https://bod-er-default-rtdb.firebaseio.com',
    storageBucket: 'bod-er.appspot.com',
  );

}